name: Run Flask Backend Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit and integration tests
      run: |
        echo "Running unit + integration tests..."
        export PYTHONPATH=.
        pytest -v tests/test_backend_app.py tests/integration/

    - name: Run system tests
      run: |
        echo "Running system tests..."
        export PYTHONPATH=.
        pytest -v tests/system/

    - name: Run system integration tests
      run: |
        echo "Running system integration tests..."
        export PYTHONPATH=.
        pytest -v tests/system_integration/
